version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "consumer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1009yagqvxqps"
s3_prefix = "consumer"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=788406368930.dkr.ecr.us-east-2.amazonaws.com/consumerlautaha"]
